// Copyright 2021 Kurguzikov Kirill

#ifndef MODULES_TASK_1_KURGUZIKOV_STRIPING_SIGNS_VECTOR_KURGUZIKOV_STRIPING_SIGNS_VECTOR_H_
#define MODULES_TASK_1_KURGUZIKOV_STRIPING_SIGNS_VECTOR_KURGUZIKOV_STRIPING_SIGNS_VECTOR_H_

int sequentialCount(int* vect, int size);
int parallelCount(int* vect, int size);
int* getRandomValue(int size);

#endif  // MODULES_TASK_1_KURGUZIKOV_STRIPING_SIGNS_VECTOR_KURGUZIKOV_STRIPING_SIGNS_VECTOR_H_
