// Copyright 2021 Kuklin Andrey
#ifndef MODULES_TASK_2_KUKLIN_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
#define MODULES_TASK_2_KUKLIN_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_

#include <mpi.h>

MPI_Comm GetlinearTopologyComm(MPI_Comm comm);

#endif  //  MODULES_TASK_2_KUKLIN_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
