// Copyright 2021 Novozhilov Alexander
#ifndef MODULES_TASK_1_NOVOZHILOV_A_MAX_VALUES_IN_COLUMNS_MAX_VALUES_IN_COLUMNS_H
#define MODULES_TASK_1_NOVOZHILOV_A_MAX_VALUES_IN_COLUMNS_MAX_VALUES_IN_COLUMNS_H

#include <vector>
#include <string>



#endif  // MODULES_TASK_1_NOVOZHILOV_A_MAX_VALUES_IN_COLUMNS_MAX_VALUES_IN_COLUMNS_H
