// Copyright 2021 Zaytsev Alexander
#ifndef MODULES_TASK_2_ZAYTSEV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
#define MODULES_TASK_2_ZAYTSEV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
#include <mpi.h>
MPI_Comm Linar(const MPI_Comm comm, int size);

#endif  // MODULES_TASK_2_ZAYTSEV_A_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
