// Copyright 2021 Kolesnikov Ilya
#ifndef MODULES_TASK_2_KOLESNIKOV_RING_TOPOLOGY_KOLESNIKOV_RING_TOPOLOGY_H_
#define MODULES_TASK_2_KOLESNIKOV_RING_TOPOLOGY_KOLESNIKOV_RING_TOPOLOGY_H_
#include <mpi.h>

MPI_Comm topology_ring(const MPI_Comm comm);
#endif  // MODULES_TASK_2_KOLESNIKOV_RING_TOPOLOGY_KOLESNIKOV_RING_TOPOLOGY_H_
