// Copyright 2021 Preobrazhenskaya Yuliya
#ifndef MODULES_TASK_2_PREOBRAZHENSKAYA_Y_RING_TOPOLOGY_RING_TOPOLOGY_H_
#define MODULES_TASK_2_PREOBRAZHENSKAYA_Y_RING_TOPOLOGY_RING_TOPOLOGY_H_
#include <mpi.h>

MPI_Comm getRingTopology(const MPI_Comm comm);

#endif  // MODULES_TASK_2_PREOBRAZHENSKAYA_Y_RING_TOPOLOGY_RING_TOPOLOGY_H_
